# Uncomment the next line to define a global platform for your project

# platform :ios, '9.0'



target 'Messenger' do
  
  # Comment the next line if you don't want to use dynamic frameworks
  
  use_frameworks!
  
  
  
  # Pods for Messenger
  
  
  
  
  pod 'Gallery', '~> 2.4'
  
  
  
  pod 'Firebase', '~> 10.11'
  
  
  
  pod 'FirebaseCore', '~> 10.11'
  
  
  
  pod 'FirebaseAuth', '~> 10.11'
  
  
  
  pod 'FirebaseFirestore', '~> 10.11'
  
  
  
  pod 'FirebaseStorage', '~> 10.11'
  
  
  
  pod 'FirebaseAnalytics', '~> 10.11'
  
  
  
  pod 'FirebaseMessaging', '~> 10.11'
  
  
  
  pod 'FirebaseFirestoreSwift', '~> 10.11'
  
  
  
  pod 'RealmSwift'
  
  
  
  pod 'ProgressHUD', '~> 13.6'
  
  
  
  
  
  
  
  pod 'MessageKit'
  
  
  
  pod 'InputBarAccessoryView'
  
  
  
  pod 'YPImagePicker'
  
  
  
  pod 'SKPhotoBrowser'
  
  
end

